# Generated by Django 4.2.2 on 2023-06-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_movie_delete_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
